name: Generate distributable files (JS)
on:
  push:
    branches:
      - main
    paths:
      - "**/*.ts"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build distributable files
        run: |
          bun build --minify --target node --outdir=./dist index.ts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: generate distributable files"
          file_pattern: "dist/*.js"
